form/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views

app_name='form'
urlpatterns = [
    path('', views.index, name='index'),
    path('individual/<int:form_id>/', views.detail, name='detail'),
    path('company/<int:form_id>/', views.detail_company, name='deets'),
    path('form-individual/', views.SignupForm.as_view(), name='form'),
    path('form-company/', views.SignupFormLegal.as_view(), name='company'),
    path('saved/', views.saveform, name='saved'),
    # path('pdf/', views.GeneratePDF.as_view(), name='pdf'),
    path('<int:form>/pdf/', views.IndividualPDFView.as_view(), name='pdf'),
    path('<int:form>/compdf/', views.CompanyPDFView.as_view(), name='compdf'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
# from ./polls import views

urlpatterns = [
    path("polls/", include("polls.urls")),
    path('admin/', admin.site.urls),
    path('', include("form.urls")),
    # path('', include('social_django.urls', namespace='social')),
    # path("complete/google-oauth2", views.complete, name = "complete")
]

polls/urls.py
from django.urls import path, re_path

from . import views

app_name = 'polls'
urlpatterns = [ 
  path("", views.index, name = "index"),
  re_path("redirected/", views.redirected, name = "redirected"),
  path("neki/", views.neki, name = "neki"),
  path("logout/", views.logout, name='logout'),

]

polls/models.py
# from django.contrib import admin
# from django.contrib.auth.models import User
# from django.db import models

# from oauth2client.contrib.django_util.models import CredentialsField


# class CredentialsModel(models.Model):
#   id = models.ForeignKey(User, primary_key=True)
#   neki = models.CharField(max_length = 50)
  # credential = CredentialsField()



# Create your models here.

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from oauth2client.client import OAuth2WebServerFlow
from django.contrib.auth.models import User
import httplib2
import json
from django.contrib.auth import authenticate, login
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import logout as auth_logout

def logout(request):
    """Logs out user"""
    auth_logout(request)
    return render(request, 'form/index.html', {'logout': 'You are not logged out'})

def index(request):
  flow = getFlow()
  authUri = flow.step1_get_authorize_url()
  template = loader.get_template("polls/index.html")
  context = {
    "linkToGoogle": authUri
  }
  return HttpResponse(template.render(context, request))

def redirected(request):
  template = loader.get_template("polls/index.html")
  try:
    code = request.GET['code']
  except KeyError:
    code = ""
  try:
    err = request.GET['error']
  except KeyError:
    err = ""
  if code:
    flow = getFlow()
    credentials = flow.step2_exchange(code)
    jason = credentials.to_json()
    jason = json.loads(jason)
    username = jason['id_token']['email']
    firstname = jason['id_token']['given_name']
    lastname = jason['id_token']['family_name']
    try:
      testuser=User.objects.all()
      user = User.objects.get(username=username)
    except ObjectDoesNotExist:
      # user = User.objects.create_user(username, username, username + "asdf")
      # user.first_name = firstname
      # user.last_name = lastname
      # user.save()
      context = {
        'not_found': 'Your account was not found in the DB.'
      }
      return HttpResponse(template.render(context, request))
    authUser = authenticate(request, username = username, password = username + "asdf")
    print("auth user", authUser)
    login(request, authUser)
    return  HttpResponseRedirect("/polls/neki")
  return HttpResponse("neki pise tm ")

def getFlow():
  return OAuth2WebServerFlow(
          client_id="838728241793-11o6gg1ff636urd50agjg6s5n91ta7s6.apps.googleusercontent.com",
          client_secret="H1a3f-CwCWsQ1ZJPD3ecw9Hn",
          redirect_uri="http://localhost:8000/polls/redirected",
          scope=["https://www.googleapis.com/auth/userinfo.email", "https://www.googleapis.com/auth/userinfo.profile"])

def complete(request):
  print (request.GET[''])

def neki(request):
  print(request.user)
  template = loader.get_template("polls/index.html")
  if request.user.is_authenticated:
    context = {
      'success': 'Successfully logged in!'
    }
    return HttpResponse(template.render(context, request))
  context = {
    'not_found': 'Successfully logged in!'
  }
  return HttpResponse(template.render(context, request))
# Create your views here.

polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Loads the path to your static files -->
    {% load staticfiles %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'form/style.css' %}">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <title>BITNIK</title>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">

            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand">BITNIK</a>
            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
            {% if user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <li class="{% block albums_active %}{% endblock %}"><a href="{% url 'form:index' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; My applications</a></li>
                </ul>
            {% endif %}
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <div class="dropdown">
                          <div class="dropdown-toggle" type="button" data-toggle="dropdown">Create a new application
                            <span class="caret"></span>
                          </div>
                          <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'form:form' %}">
                                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; For private users
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'form:company' %}">
                                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; For legal representatives
                                </a>
                            </li>
                          </ul>
                        </div>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'polls:logout' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>

        </div>
    </nav>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
</body>
</html>

polls/templates/polls/index.html
{% extends 'polls/base.html' %}
{% block body %}
    {% if linkToGoogle %}
    <div class="row">
        <div class="col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6 text-center signin-window">
            <h2>Prijava z Gmail računom!</h2>
          <a class="btn-two green large" href={{linkToGoogle}}>Prijavi me</a><br />
        </div>
    </div>
    {% elif not_found %}
        <div class="row">
            <div class="col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6 text-center signin-window">
                <h2>Vaš račun ne obstaja!</h2>
                <p>
                    Za vstop v sistem žal niste avtorizirani.
                </p>
            </div>
        </div>
    {% elif success %}
        <div class="row">
            <div class="col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6 text-center signin-window">
                <h2>Prijava z Gmail računom!</h2>
                <p>
                    Prijava uspešna!
                </p>
            </div>
        </div>
    {% elif logout %}
        <div class="row">
            <div class="col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6 text-center signin-window">
                <h2>Odjava uspešna!</h2>
                <p>
                    Iz sistema ste se uspešno odjavili.
                </p>
            </div>
        </div>
    {% endif %}
{% endblock %}