form/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views

app_name='form'
urlpatterns = [
    path('', views.index, name='index'),
    path('individual/<int:form_id>/', views.detail, name='detail'),
    path('company/<int:form_id>/', views.detail_company, name='deets'),
    path('form-individual/', views.SignupForm.as_view(), name='form'),
    path('form-company/', views.SignupFormLegal.as_view(), name='company'),
    path('saved/', views.saveform, name='saved'),
    # path('pdf/', views.GeneratePDF.as_view(), name='pdf'),
    path('<int:form>/pdf/', views.IndividualPDFView.as_view(), name='pdf'),
    path('<int:form>/compdf/', views.CompanyPDFView.as_view(), name='compdf'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
# from ./polls import views

urlpatterns = [
    path("polls/", include("polls.urls")),
    path('admin/', admin.site.urls),
    path('', include("form.urls")),
    # path('', include('social_django.urls', namespace='social')),
    # path("complete/google-oauth2", views.complete, name = "complete")
]

polls/urls.py
from django.urls import path, re_path

from . import views

app_name = 'polls'
urlpatterns = [ 
  path("", views.index, name = "index"),
  re_path("redirected/", views.redirected, name = "redirected"),
  path("neki/", views.neki, name = "neki"),
  path("logout/", views.logout, name='logout'),

]

form/models.py
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField
from django.utils import timezone


# Create your models here.

ID_CHOICES = (
    ('passport', 'Passport'),
    ('id_card', 'ID card'),
    ('drivers_license', 'Drivers license'),
)
ID_ISSUER = (
    ('country', 'Country'),
    ('dmw', 'DMW'),
)
class PersonalAccount(models.Model):
    name = models.CharField('name', max_length=200, default='')
    surname = models.CharField('surname', max_length=200, default='')
    citizenship = CountryField('citizenship', blank_label='')
    birthdate = models.DateTimeField('birth date')
    birthplace = models.CharField('birth place', max_length=200)
    address = models.CharField('address (street, No., ZIP, City, Country)', max_length=400, blank=True)
    temporary_address = models.CharField('temporary address (street, No., ZIP, City, Country)', max_length=200, blank=True)
    id_type = models.CharField('type of id', max_length=200, choices=ID_CHOICES)
    id_number = models.CharField('ID number', max_length=200)
    expiry_date = models.DateTimeField('expiry date')
    tax_number = models.CharField('tax no.', max_length=200)
    phone_number = models.CharField('phone no.', max_length=200)
    email = models.EmailField('email')
    bank_account = models.CharField('bank acc no. (to deal with Bitnik)', max_length=200)

    employment_status = models.CharField('employment status', max_length=200)
    position = models.CharField('position/activity', max_length=200)

    trade_account = models.BooleanField('Opening a trade account', default=False)

    signature_customer = models.BooleanField('signature', blank=True, default=False)
    date_signed = models.DateTimeField('date signed', blank=True, default=timezone.now())
    place_signed = models.CharField('place signed', max_length=200, blank=True, default='')

    risk = models.CharField('Oznaka kategorije tveganja (po ZPPDFT-1)', max_length=200, default='', blank=True)
    politician = models.BooleanField('politično izpostavljena oseba', blank=True, default=False)
    remarks = models.TextField('Opombe', blank=True, default='')
    name_handler = models.CharField('Ime in priimek referenta', max_length=200, blank=True, default='')
    signature_handler = models.BooleanField('Podpis referenta', blank=True, default=False)
    date_handler = models.DateTimeField('Datum', blank=True, default=timezone.now())
    place_handler = models.CharField('Kraj', max_length=200, default='', blank=True)

    def get_absolute_url(self):
        return reverse('form:index')

    def __str__(self):
        return self.name + ' ' + self.surname + ' - ' + self.email


class RepresentativeAccount(models.Model):
    representative_name = models.CharField('name', max_length=200, default='')
    representative_surname = models.CharField('surname', max_length=200, default='')
    representative_citizenship = CountryField('citizenship', blank_label='')
    representative_birthdate = models.DateTimeField('birth date')
    representative_birthplace = models.CharField('birth place', max_length=200)
    representative_address = models.CharField('address (street, No., ZIP, City, Country)', max_length=200)
    representative_id_type = models.CharField('type of id', max_length=200, choices=ID_CHOICES)
    representative_id_issuer = models.CharField('id issuer', max_length=200, choices=ID_ISSUER)
    representative_id_number = models.CharField('ID number', max_length=200)
    representative_id_issued = models.DateTimeField('id date issued')
    representative_tax_number = models.CharField('tax number', max_length=200)
    representative_date_registered = models.CharField('date registered as an procurist', max_length=200)
    representative_rights = models.TextField('what rights do you have')

    representative_trade_account = models.BooleanField('Trade account', default=False)

    representative_sign_stamp = models.BooleanField('signature and stamp', blank=True, default=True)
    representative_date_signed = models.DateTimeField('date signed', blank=True, default=timezone.now())
    representative_place_signed = models.CharField('place signed', max_length=200, default='', blank=True)

    representative_risk = models.CharField('Oznaka kategorije tveganja (po ZPPDFT-1)', max_length=200, default='', blank=True)
    representative_politician = models.BooleanField('politično izpostavljena oseba', blank=True, default=False)
    representative_remarks = models.TextField('Opombe', blank=True, default='')
    representative_name_handler = models.CharField('Ime in priimek referenta', max_length=200, blank=True, default='')
    representative_signature_handler = models.BooleanField('Podpis referenta', blank=True, default=False)
    representative_date_handler = models.DateTimeField('Datum', blank=True, default=timezone.now())
    representative_place_handler = models.CharField('Kraj', max_length=200, default='', blank=True)

    company_name = models.CharField('Company name', max_length=200)
    company_address = models.CharField('Company HQ address', max_length=400)
    company_branch_address = models.CharField('Company branch address (if different)', max_length=400)
    company_registration_number = models.CharField('Company registration number', max_length=200)
    company_vat = models.CharField('Company VAT number', max_length=200)
    company_bank_account = models.CharField('Company bank account', max_length=200)

    def get_absolute_url(self):
        return reverse('form:index')

    def __str__(self):
        return self.representative_name + ' ' + self.representative_surname + ' - ' + self.company_name


class Beneficiary(models.Model):
    representative_account = models.ForeignKey(RepresentativeAccount, on_delete=models.CASCADE)
    beneficiary_name = models.CharField('birthplace', max_length=200)
    beneficiary_surname = models.CharField('birthplace', max_length=200)
    beneficiary_address = models.CharField('birthplace', max_length=200)
    beneficiary_tax = models.CharField('birthplace', max_length=200)
    beneficiary_citizenship = models.CharField('birthplace', max_length=200)
    beneficiary_relation = models.CharField('birthplace', max_length=200)
    beneficiary_relation_percentage = models.FloatField('birthplace')

form/forms.py
from django import forms
from django.forms import ModelForm
from django_countries.widgets import CountrySelectWidget

from .models import PersonalAccount, RepresentativeAccount, Beneficiary


class DateInput(forms.DateInput):
    input_type = 'date'


class PersonalAccountForm(ModelForm):

    class Meta:
        model = PersonalAccount
        fields = ['name', 'surname', 'citizenship', 'birthdate', 'birthplace', 'address', 'temporary_address', 'id_type', 'id_number', 'expiry_date', 'tax_number', 'phone_number', 'email', 'bank_account',
              'employment_status', 'position', 'trade_account']
        widgets = {
            'birthdate': DateInput(),
            'expiry_date': DateInput(),
            'citizenship': CountrySelectWidget(),

        }

class RepresentativeAccountForm(ModelForm):

    class Meta:
        model = RepresentativeAccount
        fields = ['representative_name', 'representative_surname', 'representative_citizenship', 'representative_birthdate', 'representative_birthplace', 'representative_address',
                  'representative_id_type', 'representative_id_issuer', 'representative_id_number', 'representative_id_issued', 'representative_tax_number', 'representative_date_registered', 'representative_rights',
                  'representative_trade_account', 'company_name', 'company_address', 'company_branch_address', 'company_registration_number', 'company_vat', 'company_bank_account']
        widgets = {
            'representative_birthdate': DateInput(),
            'representative_id_issued': DateInput(),
            'representative_date_registered': DateInput(),
            'representative_citizenship': CountrySelectWidget(),
        }

form/views.py
from django.shortcuts import render, get_object_or_404
from .models import PersonalAccount, RepresentativeAccount, Beneficiary
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import Http404, HttpResponse
from django.views.generic import View
from django.template.loader import get_template
from .utils import render_to_pdf
from .forms import PersonalAccountForm, RepresentativeAccountForm
from easy_pdf.views import PDFTemplateView
from django.conf import settings

# Create your views here.
# def index(request):
#     all_users = PersonalAccount.objects.filter(pk=1)
#     return render(request, 'form/index.html', {'all_users': all_users})
def index(request):
    latest_forms = PersonalAccount.objects.order_by('-name')[:5]
    latest_forms_company = RepresentativeAccount.objects.order_by('-representative_name')[:5]
    context = {'latest_forms': latest_forms, 'latest_forms_company' : latest_forms_company}
    return render(request, 'form/index.html', context)

def detail(request, form_id):
    form = get_object_or_404(PersonalAccount, pk=form_id)
    return render(request, 'form/single.html', {'form': form})

def detail_company(request, form_id):
    form = get_object_or_404(RepresentativeAccount, pk=form_id)
    return render(request, 'form/single_company.html', {'form': form})


def signup(request):
    all_users = PersonalAccount.objects.all()
    context = {'all_data': all_users}
    return render(request, 'form/index.html', context)

def saveform(request):
    all_users = get_object_or_404(PersonalAccount.objects.all())
    return render(request, 'form/base.html', {'all_data': all_users})

class SignupForm(CreateView):
    model = PersonalAccount
    form_class = PersonalAccountForm

class SignupFormLegal(CreateView):
    model = RepresentativeAccount
    form_class = RepresentativeAccountForm

# class GeneratePDF(View):
#     def get(self, request, *args, **kwargs):
#         template = get_template('form/pdf.html')
#         selected_user = PersonalAccount.objects.filter(pk=5)
#         context = {
#             'all_users': selected_user
#         }
#         pdf = render_to_pdf('form/pdf.html', context)
#         if pdf:
#             response = HttpResponse(pdf, content_type='application/pdf')
#             filename = 'formNumber_%s.pdf' % ('12324')
#             content = 'inline; filename="%s"' %(filename)
#             response['Content-Disposition'] = content
#             download = request.GET.get('download')
#             if download:
#                 content = "attachment; filename='%s'" %(filename)
#             response['Content-Disposition'] = content
#             return response
#         return HttpResponse('Not found')

class IndividualPDFView(PDFTemplateView):
    template_name = 'form/pdf.html'

    def get_context_data(self, **kwargs):
        id = kwargs['form']
        form = get_object_or_404(PersonalAccount, pk=id)
        return super(IndividualPDFView, self).get_context_data(
            pagesize='A4',
            title='Hi there!',
            form = form
        )

class CompanyPDFView(PDFTemplateView):
    template_name = 'form/compdf.html'

    def get_context_data(self, **kwargs):
        id = kwargs['form']
        form = get_object_or_404(PersonalAccount, pk=id)
        return super(CompanyPDFView, self).get_context_data(
            pagesize='A4',
            title='Hi there!',
            form = form
        )

form/templates/form/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Loads the path to your static files -->
    {% load staticfiles %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'form/style.css' %}">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <title>BITNIK</title>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">

            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand">BITNIK</a>
            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
                {% if user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <li class="{% block albums_active %}{% endblock %}"><a href="{% url 'form:index' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; My applications</a></li>
                </ul>
                {% endif %}
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <div class="dropdown">
                          <div class="dropdown-toggle" type="button" data-toggle="dropdown">Create a new application
                            <span class="caret"></span>
                          </div>
                          <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'form:form' %}">
                                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; For private users
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'form:company' %}">
                                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; For legal representatives
                                </a>
                            </li>
                          </ul>
                        </div>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'polls:logout' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>

        </div>
    </nav>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
</body>
</html>

form/templates/form/form-template.html
{% for field in form %}
    <div class="col-sm-6">
        <div class="form-group">
            <div class="col-sm-4">
                <span class="text-danger small">{{ field.errors }}</span>
            </div>
        </div>
        <label class="control-label-input col-sm-12" style="text-align:left;">{{ field.label_tag }}</label>
        <div class="col-sm-12 input-field">{{ field }}</div>
    </div>
{% endfor %}

form/templates/form/index.html
{% extends 'form/base.html' %}
    {% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'form/style.css' %}">
{% block body %}
    {% if user.is_authenticated %}
        <div class="title-applications">
            <p>
                Applications list
            </p>
        </div>
        <div>
        {% if latest_forms %}
        <div class="application-subheader">
            FIZIČNE OSEBE
        </div>
        <ul class="app-list">
            {% for form in latest_forms %}
                <li><a href="{% url 'form:detail' form.id %}">{{ form.name }} {{ form.surname }}, {{ form.email }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
            <h4 style="text-align: center">You have no individual customers</h4>
        {% endif %}
        {% if latest_forms_company %}
        <div class="application-subheader">
            PODJETJA
        </div>
        <ul class="app-list">
            {% for form in latest_forms_company %}
                <li><a href="{% url 'form:deets' form.id %}">{{ form.representative_name }} {{ form.representative_surname }} - {{ form.company_name }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
            <h4 style="text-align: center">You have no company customers</h4>
        {% endif %}
        </div>
    {% else %}
        <div class="instruction-body">
            <div class="instruction-title">
                Creating an application
            </div>
            <p class="instruction-text">
                To create an application, click on the button in the top right corner of the page.<br><br>
                If you want to collaborate with us in your private capacity (i.e., not as a legal representative of a company),
                please select the "For private users" tab.<br><br>

                For those with authorisation on behalf of a company, the "For legal representatives" tab is the right one.<br><br>

                Please review all questions carefully and don't fill in wrong information on purpose.
            </p>
        </div>
    {% endif %}
{% endblock %}

form/templates/form/signup.html
{% extends 'form/base.html' %}
{% block body %}
    {% if error_message %}
        <p>Something went wrong, please fill the form again!</p>
    {% endif %}
    <form action="{% url 'form:saved' %}" method="post">
        {% csrf_token %}
        {% include 'form/form-template.html' %}
        <input type="text" id="fullname" name="fullname" value="fullname">
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

form/templates/form/single.html
{% extends 'form/base.html' %}
    {% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'form/style.css' %}">
{% block body %}
    {% if form %}
            <div class="row form-print">
                <div class="application-header">APPLICATION - PERSONAL ACCOUNT<a href="{% url 'form:compdf' form.id %}"><span class="glyphicon glyphicon-download"></span></a><a href="{% url 'form:compdf' form.id %}"><span class="glyphicon glyphicon-print"></span></a></div>
                <div class="application-subheader">PERSONAL DATA</div>
                <div class="control-label col-sm-6">Name: <span>{{ form.name }}</span></div>
                <div class="control-label col-sm-6">Surname: <span>{{ form.surname }}</span></div>
                <div class="control-label col-sm-6">Citizenship: <span>{{ form.citizenship }}</span></div>
                <div class="control-label col-sm-6">Birth Date and Place: <span>{{ form.birthdate }}, {{ form.birthplace }}</span></div>
                <div class="control-label col-sm-12">Address (street, No., ZIP, City, Country): <span>{{ form.address }}</span></div>
                <div class="control-label col-sm-12">Temporary Address (street, No., ZIP, City, Country): <span>{{ form.temporary_address }}</span></div>
                <div class="control-label col-sm-6">Type of ID: <span>{{ form.id_type }}</span></div>
                <div class="control-label col-sm-6">ID Number: <span>{{ form.id_number }}</span></div>
                <div class="control-label col-sm-6">Expiry date: <span>{{ form.expiry_date }}</span></div>
                <div class="control-label col-sm-6">Tax No.: <span>{{ form.tax_number }}</span></div>
                <div class="control-label col-sm-6">Phone No.: <span>{{ form.phone_number }}</span></div>
                <div class="control-label col-sm-6">E-mail: <span>{{ form.email }}</span></div>
                <div class="control-label col-sm-12">Bank Acc. No. (to deal with Bitnik): <span>{{ form.bank_account }}</span></div>
                <div class="application-subheader">EMPLOYMENT</div>
                <div class="control-label col-sm-6">Employment status: <span>{{ form.employment_status }}</span></div>
                <div class="control-label col-sm-6">Position/Activity: <span>{{ form.position }}</span></div>
                <div class="application-subheader">PURPOSE OF ESTABLISHING BUSINESS RELATIONS</div>
                <div class="control-label col-sm-12">
                    <input type="checkbox" value="" checked disabled>
                    Opening a trading account
                </div>
                <div class="application-subheader">DECLARATION</div>
                <div class="control-label col-sm-12">
                    <p class="p-underline">By signing this Application i hereby guarantee and expressly:</p>
                    <p class="p-underline">
                    > agree with the General terms of service published on the website <a style="color: rgb(0, 237, 214) !important;" href="https://bitnik.eu/en/general-terms-use/" target="_blank">https://bitnik.eu/en/general-terms-use/</a><br>
                    > declare that the information stated on the Application is correct and I am obliged to report any changes of given data to Bitnik d.o.o., and hereby authorize Bitnik d.o.o. in accordance
                        with the Personal Data Protection Act (ZVOP-1), to use, process, store, integrate in databases and process it with automated processing means for the purpose of establishin a lasting business relationship.
                    </p>
                    <p class="p-underline">I confirm that I am opening this account for the purpose of trading of digital currencies into the euro and vice versa.</p>
                    <p class="p-underline">All the information in this application is confidential. Bitnik d.o.o. undertakes to protect them in accordance with the ZVOP-1. Bitnik d.o.o. will delete
                    all data collected on the basis of this Application from our database once the purpose of business relation has been achieved and/or when the legal deadline
                    which prescribes the retention period for this information expired.
                </p>
                </div>
                <div class="application-subheader">COSTUMER'S SIGNATURE</div>
                <div class="control-label col-sm-6 box-signature">
                    <p>Signature:</p>
                </div>
                <div class="control-label col-sm-6 box-signature">
                    <p>Date and Place:</p>
                </div>
                <div class="application-subheader">FILLED BY BITNIK D.O.O.</div>
                <div class="control-label col-sm-6">Oznaka kategorije tveganja (po ZPPDFT-1):</div>
                <div class="control-label col-sm-6">Politično izpostavljena oseba:  DA  NE</div>
                <div class="control-label col-sm-12">Opombe:</div>
                <div class="control-label col-sm-12">Ime in Priimek referenta:</div>
                <div class="control-label col-sm-6 box-signature-referent">Podpis:</div>
                <div class="control-label col-sm-6 box-signature-referent">Kraj in Datum:</div>
            </div>
    {% else %}
        <h3>Form seems to be broken</h3>
    {% endif %}
{% endblock %}

form/templates/form/single_company.html
{% extends 'form/base.html' %}
    {% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'form/style.css' %}">
{% block body %}
    {% if form %}
            <div class="row form-print">
                <div class="application-header">APPLICATION - LEGAL REPRESENTATIVE<a href="{% url 'form:compdf' form.id %}"><span class="glyphicon glyphicon-download"></span></a><a href="{% url 'form:compdf' form.id %}"><span class="glyphicon glyphicon-print"></span></a></div>
                <div class="application-subheader">REPRESENTATIVE DATA</div>
                <div class="control-label col-sm-6">Name: <span>{{ form.representative_name }}</span></div>
                <div class="control-label col-sm-6">Surname: <span>{{ form.representative_surname }}</span></div>
                <div class="control-label col-sm-6">Citizenship: <span>{{ form.representative_citizenship }}</span></div>
                <div class="control-label col-sm-6">Birth Date and Place: <span>{{ form.representative_birthdate }}, {{ form.representative_birthplace }}</span></div>
                <div class="control-label col-sm-12">Address (street, No., ZIP, City, Country): <span>{{ form.representative_address }}</span></div>
                <div class="control-label col-sm-6">Type of ID: <span>{{ form.representative_id_type }}</span></div>
                <div class="control-label col-sm-6">ID issuer: <span>{{ form.representative_id_issuer }}</span></div>
                <div class="control-label col-sm-6">ID Number: <span>{{ form.representative_id_number }}</span></div>
                <div class="control-label col-sm-6">ID date issued: <span>{{ form.representative_id_issued }}</span></div>
                <div class="control-label col-sm-6">Tax No.: <span>{{ form.representative_tax_number }}</span></div>
                <div class="control-label col-sm-6">Date registered as a procurist.: <span>{{ form.representative_date_registered }}</span></div>
                <div class="control-label col-sm-12">Whats rights do you have: <span>{{ form.representative_rights }}</span></div>
                <div class="application-subheader">PURPOSE OF ESTABLISHING BUSINESS RELATIONS</div>
                <div class="control-label col-sm-12">
                    <input type="checkbox" value="" checked disabled>
                    Opening a trading account
                </div>
                <div class="application-subheader">DECLARATION</div>
                <div class="control-label col-sm-12">
                    <p class="p-underline">By signing this Application i hereby guarantee and expressly:</p>
                    <p class="p-underline">
                    > agree with the General terms of service published on the website <a style="color: rgb(0, 237, 214) !important;" href="https://bitnik.eu/en/general-terms-use/" target="_blank">https://bitnik.eu/en/general-terms-use/</a><br>
                    > declare that the information stated on the Application is correct and I am obliged to report any changes of given data to Bitnik d.o.o., and hereby authorize Bitnik d.o.o. in accordance
                        with the Personal Data Protection Act (ZVOP-1), to use, process, store, integrate in databases and process it with automated processing means for the purpose of establishin a lasting business relationship.
                    </p>
                    <p class="p-underline">I confirm that I am opening this account for the purpose of trading of digital currencies into the euro and vice versa.</p>
                    <p class="p-underline">All the information in this application is confidential. Bitnik d.o.o. undertakes to protect them in accordance with the ZVOP-1. Bitnik d.o.o. will delete
                    all data collected on the basis of this Application from our database once the purpose of business relation has been achieved and/or when the legal deadline
                    which prescribes the retention period for this information expired.
                </p>
                </div>
                <div class="application-subheader">COSTUMER'S SIGNATURE</div>
                <div class="control-label col-sm-6 box-signature">
                    <p>Signature:</p>
                </div>
                <div class="control-label col-sm-6 box-signature">
                    <p>Date and Place:</p>
                </div>
                <div class="application-subheader">FILLED BY BITNIK D.O.O.</div>
                <div class="control-label col-sm-6">Oznaka kategorije tveganja (po ZPPDFT-1):</div>
                <div class="control-label col-sm-6">Politično izpostavljena oseba:  DA  NE</div>
                <div class="control-label col-sm-12">Opombe:</div>
                <div class="control-label col-sm-12">Ime in Priimek referenta:</div>
                <div class="control-label col-sm-6 box-signature-referent">Podpis:</div>
                <div class="control-label col-sm-6 box-signature-referent">Kraj in Datum:</div>
                <div class="application-subheader">COMPANY DATA</div>
                <div class="control-label col-sm-12">Company name: <span>{{ form.company_name }}</span></div>
                <div class="control-label col-sm-6">Company HQ address: <span>{{ form.company_address }}</span></div>
                <div class="control-label col-sm-6">Company branch address (if different): <span>{{ form.company_branch_address }}</span></div>
                <div class="control-label col-sm-6">Company registration number: <span>{{ form.company_registration_number }}</span></div>
                <div class="control-label col-sm-6">Company VAT number: <span>{{ form.company_vat }}</span></div>
                <div class="control-label col-sm-12">Company bank account: <span>{{ form.company_bank_account }}</span></div>

            </div>
    {% else %}
        <h3>Form seems to be broken</h3>
    {% endif %}
{% endblock %}